[project]
name = "opendss-great-expectations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "great-expectations>=1.3.12",
    "numpy==1.26.0",
    "psycopg2>=2.9.10",
    "sqlalchemy>=2.0.39",
]
